<template>
  <div class="lading-mask">
    <view
      class="loading-warp"
      :class="{
        'flex-row': direction === 'row',
        'flex-column': direction === 'column',
      }"
    >
      <view class="loadingio-spinner-dual-ball mt-16">
        <view class="ldio">
          <view class="ldio-item"></view>
          <view class="ldio-item"></view>
          <view class="ldio-item"></view>
        </view>
      </view>
      <m-text :size="24" class="block" color="grey-8">{{ text }}</m-text>
    </view>
  </div>
</template>
<script setup lang="ts">
const props = withDefaults(
  defineProps<{
    text?: string;
    direction?: 'row' | 'column';
  }>(),
  {
    text: '正在加载中…',
    direction: 'column',
  },
);
</script>

<style type="less">
.loading-warp {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 250rpx;
  height: 180rpx;
  background: #ffffff;
  box-shadow: 0rpx 8rpx 40rpx 0rpx rgba(0, 0, 0, 0.06);
  border-radius: 36rpx;
}
.flex-row {
  flex-direction: row;
}
.flex-column {
  flex-direction: column;
}

.lading-mask {
  inset: 0;
  position: fixed;
  z-index: 9999999;
  display: flex;
  align-items: center;
  justify-content: center;
}

@keyframes ldio-o {
  0% {
    opacity: 1;
    transform: translate(0 0);
  }
  49.99% {
    opacity: 1;
    transform: translate(48rpx, 0);
  }
  50% {
    opacity: 0;
    transform: translate(48rpx, 0);
  }
  100% {
    opacity: 0;
    transform: translate(0, 0);
  }
}
@keyframes ldio {
  0% {
    transform: translate(0, 0);
  }
  50% {
    transform: translate(48rpx, 0);
  }
  100% {
    transform: translate(0, 0);
  }
}
.ldio .ldio-item {
  position: absolute;
  width: 48rpx;
  height: 48rpx;
  border-radius: 50%;
  top: 26rpx;
  left: 2rpx;
}
.ldio .ldio-item:nth-child(1) {
  background: var(--v-color-primary-9);
  animation: ldio 1s linear infinite;
  animation-delay: -0.5s;
}
.ldio .ldio-item:nth-child(2) {
  background: var(--v-color-primary-7);
  animation: ldio 1s linear infinite;
  animation-delay: 0s;
}
.ldio .ldio-item:nth-child(3) {
  background: var(--v-color-primary-9);
  animation: ldio-o 1s linear infinite;
  animation-delay: -0.5s;
}
.loadingio-spinner-dual-ball {
  width: 48rpx;
  height: 48rpx;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.48);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio .ldio-item {
  box-sizing: content-box;
}
/* [ldio] generated by https://loading.io */
</style>
